### ISSUE TITLE
get_system_var is not defined

### ISSUE THREAD

**Issue by nimrod-cohen** [emreakay/CodeIgniter-Aauth#155]
while it is documented in the docs, I see no actual code for it in the current stable git v.2 version.

are you planning to release it?

thanks!

**Comment by REJack** [comment]
Since v2.5.0 `System Variables` are removed, i need to remove it from the the docs :smiley:.

A Compatibility Library is for v2.5.0 available under https://github.com/REJack/CodeIgniter-Aauth-Compat, but i recommend to use CI's [Config Class](http://www.codeigniter.com/user_guide/libraries/config.html) for System-Wide Options.

**Comment by REJack** [comment]
Docs updated.

I'll close this issue, feel free to open a new issue if you have any other question :sweat_smile:

**Comment by nimrod-cohen** [comment]
case closed :) , thanks!

-nimrod
